repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0  # Adjust the version as needed
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Adjust the version as needed
    hooks:
      - id: trailing-whitespace
        language_version: python3
        args: []  # No arguments needed to remove trailing whitespace
